### ISSUE TITLE
sms

### ISSUE THREAD

**Issue by leandrosantiagobr** [LeoDJ/M590#1]
hello, what command do i use to read received or send sms?

**Comment by LeoDJ** [comment]
I did not implement it yet (it is planned after I finish the TCP functionality), but currently I don't have the time to develop further.

Maybe look into the [TinyGSM library](https://github.com/vshymanskyy/TinyGSM), it seems to support the M590 and I will try it out too, when I get the time.

**Comment by fbiego** [comment]
Check out this code
https://github.com/fbiego/neoway_m590/blob/master/gsm_sms/gsm_sms.ino
